from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HANDBOOK_DIR = REPO_ROOT / "handbook"
RENDERED_DIR = REPO_ROOT / "rendered"
ASSETS_DIR = REPO_ROOT / "assets"
STYLES_DIR = ASSETS_DIR / "styles"
TEMPLATES_DIR = ASSETS_DIR / "templates"

EDITION_YEAR = "2026"
EDITION_LABEL = "2026 年版・第一版"
EDITION_CODE = "PATH-2026-01"
GENERATOR_LINE = "Generated by Claude Code (Anthropic) · AI-Assisted Educational Material"
SAFETY_LINE = "請對照 Robbins / WHO 等標準教科書查證使用"
BACK_COVER_TAGLINE = "十年題庫 × 趨勢解析 × 弱點補強"
LICENSE_LINE = "MIT License"

PALETTE = {
    "red": "#b8232f",
    "deep_blue": "#1c3d5a",
    "gold": "#c9a14a",
    "ink": "#1a1a1a",
    "paper": "#fbfaf6",
    "muted": "#666666",
    "rule": "#e6dfd1",
    "stripe": "#f4efe6",
}

CHAPTER_ACCENT = {
    "00": "#1c3d5a",
    "01": "#b8232f",
    "02": "#0f6e5e",
    "03": "#2c5d8a",
    "04": "#8a4a2c",
    "05": "#5a3a8a",
    "06": "#b8232f",
    "07": "#0f6e8a",
    "08": "#c9a14a",
    "09": "#7a1d2a",
}

CHAPTERS = [
    {
        "num": "00",
        "slug": "overview",
        "source": "00-overview.md",
        "title_zh": "教學總指南",
        "title_en": "Master Overview",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-00 overview",
        "font_size_pt": 11,
    },
    {
        "num": "01",
        "slug": "molecular-cheatsheet",
        "source": "01-molecular-cheatsheet.csv",
        "title_zh": "分子・疾病・治療 速查表",
        "title_en": "Molecular–Disease–Therapy Cheatsheet",
        "orient": "landscape",
        "kind": "csv",
        "body_class": "ch-01 landscape cheatsheet",
        "font_size_pt": 9,
    },
    {
        "num": "02",
        "slug": "mock-exam-blank",
        "source": "02-mock-exam-blank.md",
        "title_zh": "模擬考卷・答題卷",
        "title_en": "Mock Exam · Blank Sheet",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-02 worksheet",
        "font_size_pt": 11,
    },
    {
        "num": "03",
        "slug": "mock-exam-key",
        "source": "03-mock-exam-key.md",
        "title_zh": "模擬考卷・詳解版",
        "title_en": "Mock Exam · Answer Key",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-03 solutions",
        "font_size_pt": 10.5,
    },
    {
        "num": "04",
        "slug": "confusion-pairs",
        "source": "04-confusion-pairs.md",
        "title_zh": "易混淆配對題卡",
        "title_en": "Confusion-Pair Flashcards",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-04 compare",
        "font_size_pt": 10.5,
    },
    {
        "num": "05",
        "slug": "12week-syllabus",
        "source": "05-12week-syllabus.md",
        "title_zh": "12 週教學大綱",
        "title_en": "12-Week Teaching Syllabus",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-05 syllabus",
        "font_size_pt": 10.5,
    },
    {
        "num": "06",
        "slug": "high-frequency-diseases",
        "source": "06-high-frequency-diseases.md",
        "title_zh": "歷年高頻疾病清單",
        "title_en": "High-Frequency Disease Index",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-06 freq",
        "font_size_pt": 10,
    },
    {
        "num": "07",
        "slug": "ihc-marker-cheatsheet",
        "source": "07-ihc-marker-cheatsheet.md",
        "title_zh": "IHC Marker 速查表",
        "title_en": "IHC Marker Cheatsheet",
        "orient": "landscape",
        "kind": "markdown",
        "body_class": "ch-07 landscape ihc",
        "font_size_pt": 9.5,
    },
    {
        "num": "08",
        "slug": "buzzword-cheatsheet",
        "source": "08-buzzword-cheatsheet.md",
        "title_zh": "Buzzword 速查表",
        "title_en": "Pathology Buzzword Index",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-08 buzzword",
        "font_size_pt": 10,
    },
    {
        "num": "09",
        "slug": "weak-spot-cards",
        "source": "09-weak-spot-cards.md",
        "title_zh": "弱點補強 14 題卡",
        "title_en": "Weak-Spot Remediation · 14 Cards",
        "orient": "portrait",
        "kind": "markdown",
        "body_class": "ch-09 cards",
        "font_size_pt": 10.5,
    },
]


def chapter_by_num(num: str) -> dict:
    for ch in CHAPTERS:
        if ch["num"] == num:
            return ch
    raise KeyError(f"chapter not found: {num}")


def output_path(num: str) -> Path:
    ch = chapter_by_num(num)
    return RENDERED_DIR / f"{num}-{ch['slug']}.pdf"


MASTER_OUTPUT = RENDERED_DIR / "00-master-edition.pdf"

STYLESHEETS_ORDER = [
    "00_reset.css",
    "01_page.css",
    "02_typography.css",
    "03_components.css",
    "04_chapters.css",
    "05_cover.css",
]


def stylesheet_paths() -> list[Path]:
    return [STYLES_DIR / name for name in STYLESHEETS_ORDER]
