from __future__ import annotations

from jinja2 import Environment, FileSystemLoader, select_autoescape

from . import config as cfg


def _env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(cfg.TEMPLATES_DIR)),
        autoescape=select_autoescape(["html", "j2"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env


def _common_ctx() -> dict:
    return {
        "edition_year": cfg.EDITION_YEAR,
        "edition_label": cfg.EDITION_LABEL,
        "edition_code": cfg.EDITION_CODE,
        "generator_line": cfg.GENERATOR_LINE,
        "safety_line": cfg.SAFETY_LINE,
        "back_cover_tagline": cfg.BACK_COVER_TAGLINE,
        "license_line": cfg.LICENSE_LINE,
        "chapters": cfg.CHAPTERS,
        "palette": cfg.PALETTE,
        "chapter_accent": cfg.CHAPTER_ACCENT,
    }


def _wrap(body_html: str, body_class: str, extra_css: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
<meta charset="utf-8">
<title>病理科國考總複習</title>
{_link_stylesheets()}
<style>{extra_css}</style>
</head>
<body class="doc {body_class}">
{body_html}
</body>
</html>"""


def _link_stylesheets() -> str:
    links = []
    for path in cfg.stylesheet_paths():
        links.append(f'<link rel="stylesheet" href="{path.as_uri()}">')
    return "\n".join(links)


def _render_template(name: str, **ctx) -> str:
    return _env().get_template(name).render(**ctx)


def render_cover(mode: str, chapter: dict | None = None) -> str:
    ctx = _common_ctx()
    ctx.update(mode=mode, chapter=chapter)
    inner = _render_template("cover.html.j2", **ctx)
    return _wrap(inner, "page-cover")


def render_colophon() -> str:
    ctx = _common_ctx()
    ctx.update(mode="master")
    inner = _render_template("colophon.html.j2", **ctx)
    return _wrap(inner, "page-colophon")


def render_toc(toc_entries: list[dict]) -> str:
    ctx = _common_ctx()
    ctx.update(mode="master", toc_entries=toc_entries)
    inner = _render_template("toc.html.j2", **ctx)
    return _wrap(inner, "page-toc")


def render_divider(chapter: dict, mode: str = "single") -> str:
    ctx = _common_ctx()
    ctx.update(mode=mode, ch=chapter, chapter=chapter)
    inner = _render_template("chapter_divider.html.j2", **ctx)
    return _wrap(inner, "page-divider")


def render_body(chapter: dict, body_html: str) -> str:
    body_class = f"page-body {chapter['body_class']}"
    inner = (
        f'<section class="chapter-body {chapter["body_class"]}" '
        f'id="ch-{chapter["num"]}-body" '
        f'data-chapter-num="{chapter["num"]}">\n'
        f"{body_html}\n"
        f"</section>"
    )
    return _wrap(inner, body_class)


def render_back_cover() -> str:
    ctx = _common_ctx()
    inner = _render_template("back_cover.html.j2", **ctx)
    return _wrap(inner, "page-back-cover")


def header_template(chapter: dict) -> str:
    return f"""<div style="font-family: 'Noto Sans TC', sans-serif; font-size: 8pt; color: #666; padding: 0 16mm; width: 100%; box-sizing: border-box; display: flex; justify-content: space-between; align-items: center; border-bottom: 0.5pt solid #c9a14a; padding-bottom: 2mm; margin-top: 5mm;">
  <span>{chapter['title_zh']}</span>
  <span>病理科國考總複習 · 章 {chapter['num']}</span>
</div>"""


def footer_template(chapter: dict | None = None) -> str:
    label = "AI-assisted · verify with Robbins"
    if chapter is None:
        label = "Generated by Claude Code · AI-Assisted"
    return f"""<div style="font-family: 'Noto Sans TC', sans-serif; font-size: 7.5pt; color: #888; padding: 0 16mm; width: 100%; box-sizing: border-box; display: flex; justify-content: space-between; align-items: center; margin-bottom: 5mm;">
  <span>{label}</span>
  <span style="color: #1c3d5a; font-weight: 600;"><span class="pageNumber"></span> / <span class="totalPages"></span></span>
</div>"""


def empty_header() -> str:
    return '<div style="display: none;"></div>'
